[package]
name = "pdfrust"
description = "PDF parser"
license-file = "LICENSE"
version = "0.5.0"
edition = "2021"

[dependencies]
flate2 = { version = "1.0.17", features = ["zlib-ng"], default-features = false }
